on:
  schedule:
    - cron: '6 * * * *'

jobs:
  health_check_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: https://blue-glade-4018.fly.dev/health
          max-attempts: 3
          retry-delay: 5s